# Generated by Django 4.2.13 on 2024-07-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('value', models.TextField(max_length=10)),
                ('risk', models.TextField(max_length=10)),
            ],
        ),
    ]
