# Generated by Django 4.2.13 on 2024-07-07 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='document',
            new_name='TableActives',
        ),
    ]
